"""add_voice_sales_analytics_vector_v2

Revision ID: 0657b06e8fd9
Revises: 82c74e3c4c4e
Create Date: 2026-01-10 04:47:36.683575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '0657b06e8fd9'
down_revision: Union[str, Sequence[str], None] = '82c74e3c4c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable vector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_interactions_project_id'), 'sales_interactions', ['project_id'], unique=False)
    op.create_index(op.f('ix_sales_interactions_session_id'), 'sales_interactions', ['session_id'], unique=True)
    op.create_table('analytics_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('bi_reasoning', sa.Text(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_results_submission_id'), 'analytics_results', ['submission_id'], unique=False)
    op.create_table('voice_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('tone_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_results_submission_id'), 'voice_results', ['submission_id'], unique=False)
    op.drop_index(op.f('ix_agent_metrics_date'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index(op.f('ix_knowledge_base_country'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_regulation'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_agent_executions_started_at'), table_name='agent_executions')
    op.alter_column('agent_traces', 'execution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('analytics_reports', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.drop_index(op.f('ix_compliance_checks_check_date'), table_name='compliance_checks')
    op.drop_index(op.f('ix_content_chunks_chunk_index'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_submission_chunk'), table_name='content_chunks')
    op.drop_constraint(op.f('deep_analysis_check_id_key'), 'deep_analysis', type_='unique')
    op.drop_index(op.f('ix_deep_analysis_check_id'), table_name='deep_analysis')
    op.create_index(op.f('ix_deep_analysis_check_id'), 'deep_analysis', ['check_id'], unique=True)
    op.drop_table_comment(
        'deep_analysis',
        existing_comment='Stores complete deep analysis for a submission as a single JSON document',
        schema=None
    )
    op.alter_column('rules', 'points_deduction',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Point deduction value for compliance score calculation',
               existing_comment='Point deduction value for compliance score calculation. Negative values indicate penalties.',
               existing_nullable=False,
               existing_server_default=sa.text("'-5.00'::numeric"))
    op.alter_column('rules', 'created_by',
               existing_type=sa.UUID(),
               comment='Super admin who created this rule',
               existing_comment='UUID of the super admin who created this rule. NULL for system-seeded rules.',
               existing_nullable=True)
    op.alter_column('rules', 'is_auto_generated',
               existing_type=sa.BOOLEAN(),
               comment='True if rule was auto-generated from onboarding',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rules', 'generated_from_industry',
               existing_type=sa.VARCHAR(length=100),
               comment="Industry context for auto-generated rules (e.g., 'insurance', 'healthcare')",
               existing_nullable=True)
    op.alter_column('rules', 'generation_source',
               existing_type=sa.TEXT(),
               comment='Source URL or search query used to generate this rule',
               existing_nullable=True)
    op.alter_column('rules', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment='AI confidence in rule extraction (0.0-1.0)',
               existing_nullable=True)
    op.drop_index(op.f('ix_tool_invocations_created_at'), table_name='tool_invocations')
    op.drop_constraint(op.f('user_configs_user_id_key'), 'user_configs', type_='unique')
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=True)
    # op.drop_index(op.f('ix_violations_category'), table_name='violations')
    # op.drop_index(op.f('ix_violations_category_severity'), table_name='violations')
    # op.drop_index(op.f('ix_violations_check_id_category'), table_name='violations')
    # op.drop_index(op.f('ix_violations_severity'), table_name='violations')
    # op.alter_column('violations', 'severity',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    # op.alter_column('violations', 'category',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=False)
    # op.drop_index(op.f('ix_violations_category'), table_name='violations')
    # op.drop_index(op.f('ix_violations_category_severity'), table_name='violations')
    # op.drop_index(op.f('ix_violations_check_id_category'), table_name='violations')
    # op.drop_index(op.f('ix_violations_severity'), table_name='violations')
    op.add_column('voice_reports', sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('voice_reports', sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('voice_reports', sa.Column('business_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('voice_reports', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('voice_reports', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_reports', 'embedding')
    op.drop_column('voice_reports', 'risk_score')
    op.drop_column('voice_reports', 'business_insights')
    op.drop_column('voice_reports', 'violations')
    op.drop_column('voice_reports', 'extracted_entities')
    op.create_index(op.f('ix_violations_severity'), 'violations', ['severity'], unique=False)
    # op.create_index(op.f('ix_violations_check_id_category'), 'violations', ['check_id', 'category'], unique=False)
    # op.create_index(op.f('ix_violations_category_severity'), 'violations', ['category', 'severity'], unique=False)
    # op.create_index(op.f('ix_violations_category'), 'violations', ['category'], unique=False)
    # op.alter_column('violations', 'category',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    # op.alter_column('violations', 'severity',
    #            existing_type=sa.String(length=20),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_configs_user_id_key'), 'user_configs', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tool_invocations_created_at'), 'tool_invocations', ['created_at'], unique=False)
    op.alter_column('rules', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='AI confidence in rule extraction (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('rules', 'generation_source',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Source URL or search query used to generate this rule',
               existing_nullable=True)
    op.alter_column('rules', 'generated_from_industry',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Industry context for auto-generated rules (e.g., 'insurance', 'healthcare')",
               existing_nullable=True)
    op.alter_column('rules', 'is_auto_generated',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if rule was auto-generated from onboarding',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rules', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID of the super admin who created this rule. NULL for system-seeded rules.',
               existing_comment='Super admin who created this rule',
               existing_nullable=True)
    op.alter_column('rules', 'points_deduction',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Point deduction value for compliance score calculation. Negative values indicate penalties.',
               existing_comment='Point deduction value for compliance score calculation',
               existing_nullable=False,
               existing_server_default=sa.text("'-5.00'::numeric"))
    op.create_table_comment(
        'deep_analysis',
        'Stores complete deep analysis for a submission as a single JSON document',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_deep_analysis_check_id'), table_name='deep_analysis')
    op.create_index(op.f('ix_deep_analysis_check_id'), 'deep_analysis', ['check_id'], unique=False)
    op.create_unique_constraint(op.f('deep_analysis_check_id_key'), 'deep_analysis', ['check_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_content_chunks_submission_chunk'), 'content_chunks', ['submission_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_content_chunks_chunk_index'), 'content_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_compliance_checks_check_date'), 'compliance_checks', ['check_date'], unique=False)
    op.drop_column('analytics_reports', 'embedding')
    op.alter_column('agent_traces', 'execution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_agent_executions_started_at'), 'agent_executions', ['started_at'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('regulation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_pkey'))
    )
    op.create_index(op.f('ix_knowledge_base_regulation'), 'knowledge_base', ['regulation_name'], unique=False)
    op.create_index(op.f('ix_knowledge_base_country'), 'knowledge_base', ['country_code'], unique=False)
    op.create_table('agent_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_invocations', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_execution_time_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_cost_usd', sa.NUMERIC(precision=10, scale=6), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_metrics_pkey')),
    sa.UniqueConstraint('date', 'agent_type', 'tool_name', name=op.f('uq_agent_metrics_date_type_tool'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_agent_metrics_date'), 'agent_metrics', ['date'], unique=False)
    op.drop_index(op.f('ix_voice_results_submission_id'), table_name='voice_results')
    op.drop_table('voice_results')
    op.drop_index(op.f('ix_analytics_results_submission_id'), table_name='analytics_results')
    op.drop_table('analytics_results')
    op.drop_index(op.f('ix_sales_interactions_session_id'), table_name='sales_interactions')
    op.drop_index(op.f('ix_sales_interactions_project_id'), table_name='sales_interactions')
    op.drop_table('sales_interactions')
    # ### end Alembic commands ###
