"""create_projects_table

Revision ID: c6c5e04af60a
Revises: a2cb211cbe7f
Create Date: 2025-12-11 08:30:00.419634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6c5e04af60a'
down_revision: Union[str, Sequence[str], None] = 'a2cb211cbe7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_table('guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidelines_project_id'), 'guidelines', ['project_id'], unique=False)
    
    # Add columns to rules
    op.add_column('rules', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('rules', sa.Column('source_guideline_id', sa.UUID(), nullable=True))
    
    # Check if we need to modify rules columns (safe to keep if they might already match)
    # Using execute to check active schema state carefully or just alter
    # For POC, assuming these are new modifications needed
    
    op.create_index(op.f('ix_rules_project_id'), 'rules', ['project_id'], unique=False)
    op.create_index(op.f('ix_rules_source_guideline_id'), 'rules', ['source_guideline_id'], unique=False)
    op.create_foreign_key(None, 'rules', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rules', 'guidelines', ['source_guideline_id'], ['id'], ondelete='SET NULL')
    
    # Add columns to submissions
    op.add_column('submissions', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_project_id'), table_name='submissions')
    op.drop_column('submissions', 'project_id')
    
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_index(op.f('ix_rules_source_guideline_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_project_id'), table_name='rules')
    op.drop_column('rules', 'source_guideline_id')
    op.drop_column('rules', 'project_id')
    
    op.drop_index(op.f('ix_guidelines_project_id'), table_name='guidelines')
    op.drop_table('guidelines')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
