"""add_policy_model_retry

Revision ID: fa4702d96d2c
Revises: 0657b06e8fd9
Create Date: 2026-01-10 05:14:12.885131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4702d96d2c'
down_revision: Union[str, Sequence[str], None] = '0657b06e8fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
